# Generated by Django 4.2.6 on 2023-11-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('especie', models.CharField(max_length=50)),
                ('idade', models.IntegerField(max_length=2)),
                ('raca', models.CharField(max_length=50)),
                ('historico_saude', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Cadastro de Animal',
                'verbose_name_plural': 'Cadastros de Animais',
                'ordering': ['-idade'],
            },
        ),
    ]
