# Generated by Django 4.2.6 on 2023-11-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
