# Generated by Django 4.2.6 on 2023-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animal_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='genero',
            field=models.CharField(choices=[(0, 'Feminino'), (1, 'Masculino')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
    ]
