# Generated by Django 4.2.6 on 2023-11-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animal_genero_animal_peso_alter_animal_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=50, null=True),
        ),
    ]
