# Generated by Django 4.2.6 on 2023-11-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_alter_animal_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='genero',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=50, null=True),
        ),
    ]
