# Generated by Django 4.2.6 on 2023-11-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_alter_animal_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
