# Generated by Django 4.2.6 on 2023-11-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0006_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='../base/static/images'),
        ),
    ]
