# Generated by Django 4.2.6 on 2023-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0011_alter_animal_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(upload_to='animais/images/'),
        ),
    ]
