# Generated by Django 4.2.6 on 2023-11-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaladocao',
            name='temAnimal',
            field=models.BooleanField(default=False),
        ),
    ]
