# Generated by Django 4.2.6 on 2023-11-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_animaladocao_temanimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaladocao',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de Adoção', 'verbose_name_plural': 'Formulários de Adoções'},
        ),
        migrations.AlterField(
            model_name='animaladocao',
            name='temAnimal',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False),
        ),
    ]
