# Generated by Django 4.2.6 on 2023-12-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_animaladocao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladocao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Recusada', 'Recusada')], default='Pendente', max_length=22),
        ),
    ]
