# Generated by Django 4.2.6 on 2023-12-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_animaladocao_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaladocao',
            old_name='animal',
            new_name='animal_id',
        ),
    ]
