# Generated by Django 4.2.6 on 2023-12-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_animal_animaladocao_animal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaladocao',
            old_name='animal_id',
            new_name='animal',
        ),
    ]
