# Generated by Django 4.2.6 on 2023-12-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_animal_id_animaladocao_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaladocao',
            name='animal',
        ),
    ]
