# Generated by Django 4.2.6 on 2023-12-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0014_alter_animal_imagem'),
        ('base', '0008_remove_animaladocao_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladocao',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animais.animal'),
        ),
    ]
