# Generated by Django 4.2.6 on 2023-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_animaladocao_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaladocao',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
